[package]
name = "wizquicklaunch3r"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["handleapi", "winuser", "processthreadsapi"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = "3.0"